Repository w3c/wot-thing-description, pull requests merged in 2019-05, with the labels that each got.

#672 Timezone of DateTime serialization in TD
  index.html
  index.template.html
Labels: Needs review

#690 Annotate at-risk features with searchable text
  index.html
  index.template.html
  ontology/wot-security.ttl
  testing/report.html
Labels: by CR transition

#691 Edited UML diagrams in Section 5.1 Overview (bis)
  images/uml-overview.pptx
  index.html
  index.template.html
  visualization/hypermedia.png
  visualization/json-schema.png
  visualization/td.png
  visualization/wot-security.png
Labels: Editorial
