Repository w3c/wot-thing-description, pull requests merged in 2019-06, with the labels that each got.

#759 Fix some editorial issues (replaces PR #758)
  index.html
  index.template.html
  ontology/hypermedia.ttl
  ontology/td.ttl
  validation/td-validation.ttl
Labels: Editorial

#688 Refactored RDF examples for simplicity
  images/uml-overview.pptx
  index.html
  index.template.html
  visualization/td.png
Labels: Editorial

#777 Add RFC references for security schemes
  index.html
  ontology/wot-security.ttl
  ontology/wotsec.html
  render.sh
Labels: Editorial, by PR transition

#780 Figure 2 title was changed to "Data Schema Vocabulary" (Issue #700)
  index.html
  index.template.html
Labels: by PR transition
