Repository w3c/wot-thing-description, pull requests merged in 2022-02, with the labels that each got.

#1368 Adding `$id` to JSON Schema
  index.html
  index.template.html
  validation/td-json-schema-validation.json
  validation/tm-json-schema-validation.json
  validation/tmSchemaGenerator.js
Labels: V1.1, non-normative

#1377 Add dataResponse to event affordance
  context/td-context-1.1.jsonld
  ontology/td.ttl
Labels: V1.1

#1376 refactor: remove MD5 from alg example list
  index.html
  validation/td-validation.ttl
Labels: V1.1

#1380 Add profile to JSON Schema
  index.html
  validation/td-json-schema-validation.json
  validation/tm-json-schema-validation.json
Labels: V1.1, non-normative

#1383 Top level URI Variables
  index.html
  index.template.html
  ontology/td.html
  validation/td-json-schema-validation.json
  validation/td-validation.ttl
  validation/tm-json-schema-validation.json
  visualization/td.svg
Labels: V1.1, normative change
