Repository w3c/wot-thing-description, pull requests merged in 2022-05, with the labels that each got.

#1327 fix(ontology): Use ontology URI and dcterms instead of dc
  ontology/td.ttl
Labels: Editorial, Needs discussion, non-normative

#1478 support transitive extension in TM definitions
  index.html
  index.template.html
Labels: non-normative

#1484 chore: fix filename bug in assertion sync workflow
  .github/workflows/assertion-sync.yml
Labels: non-normative

#1485 remove tag text in validation sections
  index.html
  index.template.html
Labels: non-normative

#1486 structure @context rules
  index.html
  validation/td-validation.ttl
Labels: non-normative

#1480 default values for read/writeOnly only in PropertyAffordance definitions
  index.html
  index.template.html
Labels: normative change

#1476 Add section about IANA Thing Model content type registration
  index.html
  index.template.html
Labels: normative change

#1489 fix: check whether script runs with ReSpec or pure HTML
  index.html
  index.template.html
Labels: non-normative

#1493 Add table on how to link op values to data schema related terms
  index.html
  validation/td-validation.ttl
Labels: non-normative

#1494 Add `@context` requirement for TMs
  index.html
  index.template.html
Labels: normative change

#1491 Synchronous keyword to actions
  context/td-context-1.1.jsonld
  context/td-context.jsonld
  context/td-context.ttl
  index.html
  ontology/td.html
  ontology/td.ttl
  validation/td-json-schema-validation.json
  validation/td-validation.ttl
  validation/tm-json-schema-validation.json
  validation/tmSchemaGenerator.js
  visualization/td.svg
Labels: normative change

#1507 Beautify infromation model drawings
  index.html
  index.template.html
  visualization/hctl.png
  visualization/hctl.svg
  visualization/jsonschema.png
  visualization/jsonschema.svg
  visualization/td.png
  visualization/td.svg
  visualization/wotsec.png
  visualization/wotsec.svg
Labels: non-normative

#1506 Note about the id derivation from TM
  index.html
  index.template.html
Labels: non-normative

#1499 Reference to string-specific directional information
  index.html
  validation/td-validation.ttl
Labels: normative change
