Repository w3c/wot-thing-description, pull requests merged in 2022-08, with the labels that each got.

#1659 Make some text assertive
  index.html
  validation/td-validation.ttl
Labels: normative change

#1657 add semantic tag definition and links to it
  index.html
  index.template.html
  templates.sparql
Labels: non-normative

#1649 Allow flexible chartacter for self-contained TDs from TMs
  index.html
  index.template.html
Labels: by CR transition, normative change

#1652 any type explaination
  index.html
  validation/td-validation.ttl
Labels: by CR transition

#1558 addresses CR 1.1 candidate review from Oracle
  index.html
  index.template.html
  ontology/jsonschema.html
  ontology/jsonschema.ttl
  ontology/td.html
  ontology/td.ttl
  ontology/wotsec.html
  ontology/wotsec.ttl
  package-lock.json
  validation/td-validation.ttl
Labels: by CR transition, normative change
