Repository w3c/wot-thing-description, pull requests merged in 2022-01, with the labels that each got.

#1332 fix: some HTML markup issues
  index.html
  index.template.html
Labels: Editorial, 2nd WD

#1333 update abstract
  index.html
  index.template.html
Labels: Editorial, 2nd WD

#1334 TD Info Model fixes
  index.html
  index.template.html
  validation/td-validation.ttl
Labels: Editorial, 2nd WD

#1335 fix: typos and grammatical errors
  index.html
  index.template.html
Labels: Editorial, 2nd WD

#1336 fix: some internal links
  index.html
  index.template.html
Labels: Editorial, 2nd WD

#1337 fix: minor singular vs plural issue
  index.html
  index.template.html
Labels: Editorial, 2nd WD

#1344 fix: object definition ref in ObjectSchema
  index.html
  validation/td-validation.ttl
Labels: Editorial, 2nd WD

#1339 update assertion td-context-ns-thing-mandatory
  index.html
  validation/td-validation.ttl
Labels: 2nd WD, normative change

#1283 update webhooks example
  index.html
  index.template.html
  ontology/td.ttl
  validation/td-validation.ttl
Labels: 2nd WD, non-normative
