Repository w3c/wot-thing-description, pull requests merged in 2022-06, with the labels that each got.

#1524 Add old context value
  validation/td-json-schema-validation.json
Labels: non-normative

#1532 Allow placeholder for required and enum in TMs
  validation/td-json-schema-validation.json
  validation/test.js
  validation/tm-json-schema-validation.json
  validation/tmSchemaGenerator.js
Labels: non-normative

#1544 Add RFC9200 reference
  index.html
  index.template.html
Labels: Security

#1543 Revise statements about auto SecurityScheme
  index.html
  index.template.html
  ontology/wotsec.html
  ontology/wotsec.ttl
  validation/td-validation.ttl
Labels: Security

#1542 Discuss Secure Transport in Security Schemes
  index.html
  index.template.html
  ontology/wotsec.html
  ontology/wotsec.ttl
  validation/td-validation.ttl
Labels: Security

#1547 Improve Privacy Assertions
  index.html
  index.template.html
Labels: Privacy
