Repository w3c/wot-thing-description, pull requests merged in 2023-11, with the labels that each got.

#1911 Figure Update Process Documentation
  publication/README.md
Labels: Editorial

#1913 TD Figures Update
  publication/ver11/7-rec/visualization/hctl.png
  publication/ver11/7-rec/visualization/hctl.svg
  publication/ver11/7-rec/visualization/jsonschema.png
  publication/ver11/7-rec/visualization/jsonschema.svg
  publication/ver11/7-rec/visualization/td.png
  publication/ver11/7-rec/visualization/td.svg
  publication/ver11/7-rec/visualization/wotsec.png
  publication/ver11/7-rec/visualization/wotsec.svg
  visualization/hctl.svg
  visualization/jsonschema.svg
  visualization/td.svg
  visualization/tm.svg
  visualization/wotsec.svg
Labels: Editorial

#1912 TM Regex fix
  validation/tm-json-schema-validation.json
  validation/tmSchemaGenerator.js
Labels: Editorial, JSON Schema, Thing Model

#1916 Sync Resources Folder
  publication/ver11/7-resources/ontology/wotsec.html
  publication/ver11/7-resources/ontology/wotsec.ttl
  publication/ver11/7-resources/validation/tm-json-schema-validation.json
Labels: Editorial

#1917 Update version for TD/TM JSON schema changes
  validation/td-json-schema-validation.json
  validation/tm-json-schema-validation.json
Labels: Editorial, JSON Schema

#1919 WoT toolchain diagram added
  toolchain/README.md
  toolchain/wot-toolchain-bpmn.drawio
  toolchain/wot-toolchain-bpmn.png
Labels: Tooling, pipeline, useful-documentation
