Repository w3c/wot-thing-description, pull requests merged in 2023-05, with the labels that each got.

#1812 Update manual.csv
  testing/manual.csv
Labels: Testing

#1800 Mention apikey creation is only for object and arrays
  index.html
  validation/td-validation.ttl
Labels: Editorial

#1802 Fix html checker errors
  index.html
  index.template.html
  validation/td-validation.ttl
Labels: Editorial

#1790 Editorial fixes for issue 1735
  index.html
  index.template.html
  validation/td-validation.ttl
Labels: Editorial, by PR transition

#1820 Add semantic annotation def and use it
  index.html
  index.template.html
Labels: Editorial

#1821 Extend proxy-to description
  index.html
  validation/td-validation.ttl
Labels: Editorial

#1822 Explain multiple inputs
  index.html
  validation/td-validation.ttl
Labels: Editorial

#1826 Resolve privacy-immutable-id-as-property
  index.html
  index.template.html
Labels: by PR transition

#1811 Resolve 3 editors notes
  index.html
  index.template.html
  validation/td-validation.ttl
Labels: Editorial

#1783 Remove at risk items in the sotd section
  index.html
  index.template.html
Labels: Editorial, by PR transition

#1836 Add defaults to appendix examples
  index.html
  index.template.html
Labels: Editorial
